#!/usr/bin/env node
/**
 * Collect the real app's pixels for the demo video.
 *
 * ## The rule this file exists to enforce
 *
 * Every frame of AfyaCore in the video is a photograph of the running
 * application. Nothing here is a mockup, a Figma export, or a React
 * re-creation of the UI, and Remotion is never asked to draw the app — only to
 * arrange, caption and animate frames the app itself produced. A demo video
 * for a track that asks for an operational end-to-end demonstration should not
 * contain a single pixel the software cannot produce on demand.
 *
 * Two sources, both real:
 *
 *  1. `docs/screenshots/*.webp`, regenerated by `npm run screenshots` against
 *     the production build. Reused rather than re-captured so the video and the
 *     README can never drift apart.
 *
 *  2. A short live sequence captured here, for the one thing a still cannot
 *     show: the app being used with the network switched off. That is the
 *     claim the project rests on and the moment worth watching happen.
 *
 *   npm run build && npm run preview     # in the repo root
 *   npm --prefix video run capture
 */
import { access, copyFile, mkdir, readdir, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import puppeteer from '../node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '..')
const SHOTS = join(repo, 'docs', 'screenshots')
const PUBLIC = join(here, 'public')
const BASE = process.env.AFYACORE_URL ?? 'http://localhost:4173'

const CHROME_CANDIDATES = [
  process.env.CHROME_PATH,
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
].filter(Boolean)

async function findChrome() {
  for (const p of CHROME_CANDIDATES) {
    try {
      await access(p)
      return p
    } catch {
      /* next */
    }
  }
  throw new Error('No Chromium. Set CHROME_PATH.')
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function settle(page) {
  await page.waitForFunction(
    () => document.querySelector('main') !== null || document.querySelector('[data-lock]') !== null,
    { timeout: 20_000 },
  )
  await sleep(400)
}

async function clickText(page, selector, pattern) {
  const handle = await page.evaluateHandle(
    (sel, src) => {
      const re = new RegExp(src, 'i')
      return [...document.querySelectorAll(sel)].find((el) => re.test((el.textContent ?? '').trim())) ?? null
    },
    selector,
    pattern.source ?? pattern,
  )
  const el = handle.asElement()
  if (!el) throw new Error(`no ${selector} matching ${pattern}`)
  await el.click()
  await settle(page)
}

async function unlockIfNeeded(page) {
  const locked = await page.evaluate(() =>
    [...document.querySelectorAll('button')].some(
      (b) => (b.textContent ?? '').trim().toLowerCase() === 'unlock',
    ),
  )
  if (!locked) return
  for (const d of '4729') {
    await page.evaluate((digit) => {
      ;[...document.querySelectorAll('button')].find((b) => b.textContent?.trim() === digit)?.click()
    }, d)
  }
  await clickText(page, 'button', /^unlock$/)
  await page.waitForSelector('main', { timeout: 20_000 })
  await sleep(300)
}

/** Copy the README screenshots in, so one capture serves both. */
async function copyScreens() {
  const dest = join(PUBLIC, 'screens')
  await mkdir(dest, { recursive: true })
  const files = (await readdir(SHOTS)).filter((f) => f.endsWith('.webp'))
  if (files.length === 0) throw new Error('no screenshots; run `npm run screenshots` first')
  for (const file of files) await copyFile(join(SHOTS, file), join(dest, file))
  console.log(`  screens   ${files.length} from docs/screenshots`)
}

/**
 * The offline sequence, captured live.
 *
 * A still cannot show that the network is off and the app still works, so this
 * walks it and photographs each step. Same walk `npm run smoke` asserts, which
 * means the video cannot show something CI does not also prove.
 */
async function captureOffline() {
  const dest = join(PUBLIC, 'offline')
  await rm(dest, { recursive: true, force: true })
  await mkdir(dest, { recursive: true })

  const browser = await puppeteer.launch({
    executablePath: await findChrome(),
    headless: 'new',
    args: process.getuid?.() === 0 ? ['--no-sandbox'] : [],
  })
  const page = await browser.newPage()
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 })

  let n = 0
  const shot = async (label) => {
    const name = `${String(++n).padStart(2, '0')}-${label}.png`
    await page.screenshot({ path: join(dest, name) })
    console.log(`  offline   ${name}`)
  }

  try {
    await page.goto(BASE, { waitUntil: 'networkidle2' })
    await settle(page)

    const inputs = await page.$$('input')
    const values = ['Dr Ranaivo', '4729', '4729']
    for (let i = 0; i < values.length && i < inputs.length; i++) {
      await inputs[i].click()
      await inputs[i].type(values[i])
    }
    await clickText(page, 'button', /create account/)

    await page.goto(`${BASE}/settings`, { waitUntil: 'networkidle2' })
    await settle(page)
    await unlockIfNeeded(page)
    await clickText(page, 'button', /load demo/)
    await sleep(600)

    await page.goto(`${BASE}/patients`, { waitUntil: 'networkidle2' })
    await settle(page)
    await unlockIfNeeded(page)
    await shot('online-roster')

    // Network off. Everything after this is the claim being demonstrated.
    await page.setOfflineMode(true)
    await shot('offline-roster')

    await page.reload({ waitUntil: 'domcontentloaded' })
    await settle(page)
    await shot('offline-reload-lock')

    await unlockIfNeeded(page)
    await shot('offline-after-unlock')

    await page.goto(`${BASE}/patients`, { waitUntil: 'domcontentloaded' })
    await settle(page)
    await unlockIfNeeded(page)
    await shot('offline-roster-again')
  } finally {
    await browser.close()
  }
}

/**
 * The app's own typeface, so the video is set in the same type as the product.
 *
 * Copied from the root node_modules rather than re-downloaded: it is the exact
 * file the app ships and the service worker precaches, which is the point.
 */
async function copyFont() {
  const dest = join(PUBLIC, 'fonts')
  await mkdir(dest, { recursive: true })
  const name = 'ibm-plex-sans-latin-wght-normal.woff2'
  await copyFile(
    join(repo, 'node_modules', '@fontsource-variable', 'ibm-plex-sans', 'files', name),
    join(dest, name),
  )
  console.log(`  font      ${name}`)
}

async function main() {
  console.log('capturing the real app for the demo video\n')
  await mkdir(PUBLIC, { recursive: true })
  await copyFont()
  await copyScreens()
  await captureOffline()
  console.log('\n  -> video/public/. Every frame is the running application.')
}

main().catch((err) => {
  console.error(`capture failed: ${err.message}`)
  process.exit(1)
})
