#!/usr/bin/env node
/**
 * Collect the real app's pixels for the demo video.
 *
 * ## The rule this file exists to enforce
 *
 * Every frame of AfyaCore in the video is a photograph of the running
 * application. Nothing here is a mockup, a Figma export, or a React
 * re-creation of the UI, and Remotion is never asked to draw the app — only to
 * arrange, caption and animate frames the app itself produced. A demo video
 * for a track that asks for an operational end-to-end demonstration should not
 * contain a single pixel the software cannot produce on demand.
 *
 * Two sources, both real:
 *
 *  1. `docs/screenshots/*.webp`, regenerated by `npm run screenshots` against
 *     the production build. Reused rather than re-captured so the video and the
 *     README can never drift apart.
 *
 *  2. A short live sequence captured here, for the one thing a still cannot
 *     show: the app being used with the network switched off. That is the
 *     claim the project rests on and the moment worth watching happen.
 *
 *   npm run build && npm run preview     # in the repo root
 *   npm --prefix video run capture
 */
import { execFile, spawn } from 'node:child_process'
import { copyFile, mkdir, readdir, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'
import { fileURLToPath } from 'node:url'
import puppeteer from '../node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js'
import { findChrome, LAUNCH_ARGS } from '../scripts/find-chrome.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '..')
const SHOTS = join(repo, 'docs', 'screenshots')
const PUBLIC = join(here, 'public')
const BASE = process.env.AFYACORE_URL ?? 'http://localhost:4173'
const SYNC_PORT = Number(process.env.AFYACORE_SYNC_PORT ?? 8788)
const SYNC_URL = `http://localhost:${SYNC_PORT}`
const FACILITY = 'CSB2-Ambohidratrimo'
const run = promisify(execFile)


const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function settle(page) {
  await page.waitForFunction(
    () => document.querySelector('main') !== null || document.querySelector('[data-lock]') !== null,
    { timeout: 20_000 },
  )
  await sleep(400)
}

async function clickText(page, selector, pattern) {
  const handle = await page.evaluateHandle(
    (sel, src) => {
      const re = new RegExp(src, 'i')
      return [...document.querySelectorAll(sel)].find((el) => re.test((el.textContent ?? '').trim())) ?? null
    },
    selector,
    pattern.source ?? pattern,
  )
  const el = handle.asElement()
  if (!el) throw new Error(`no ${selector} matching ${pattern}`)
  await el.click()
  await settle(page)
}

async function unlockIfNeeded(page) {
  const locked = await page.evaluate(() =>
    [...document.querySelectorAll('button')].some(
      (b) => (b.textContent ?? '').trim().toLowerCase() === 'unlock',
    ),
  )
  if (!locked) return
  for (const d of '4729') {
    await page.evaluate((digit) => {
      ;[...document.querySelectorAll('button')].find((b) => b.textContent?.trim() === digit)?.click()
    }, d)
  }
  await clickText(page, 'button', /^unlock$/)
  await page.waitForSelector('main', { timeout: 20_000 })
  await sleep(300)
}

/** Copy the README screenshots in, so one capture serves both. */
async function copyScreens() {
  const dest = join(PUBLIC, 'screens')
  await mkdir(dest, { recursive: true })
  const files = (await readdir(SHOTS)).filter((f) => f.endsWith('.webp'))
  if (files.length === 0) throw new Error('no screenshots; run `npm run screenshots` first')
  for (const file of files) await copyFile(join(SHOTS, file), join(dest, file))
  console.log(`  screens   ${files.length} from docs/screenshots`)
}

/**
 * A throwaway sync server, so the status chip has something true to say.
 *
 * The first cut of the offline sequence never enrolled the device, and the
 * consequence only showed up when the rendered frames were compared side by
 * side: with no server configured the chip reads "Saved on device" whether the
 * network is up or down, so the online and offline shots were pixel-identical
 * in the one place a viewer would look to tell them apart. The captions
 * asserted a state change the frames did not show.
 *
 * Enrolling against a real server fixes that at the source rather than with an
 * overlay. The chip goes from a green "All synced" to a grey "Offline" because
 * the app worked out it was offline, which is the whole point of the beat, and
 * the walk now also proves enrolment and a push actually work end to end.
 *
 * The database is thrown away on every run, so this leaves nothing behind.
 */
async function startSyncServer() {
  const dbDir = join(here, '.capture')
  const dbPath = join(dbDir, 'sync.db')
  await rm(dbDir, { recursive: true, force: true })
  await mkdir(dbDir, { recursive: true })

  const env = {
    ...process.env,
    AFYACORE_DB: dbPath,
    PORT: String(SYNC_PORT),
    // The app is served from a different port, so the browser treats sync as
    // cross-origin. The server refuses every origin it was not told about.
    AFYACORE_ALLOWED_ORIGINS: BASE,
  }

  const child = spawn('node', [join(repo, 'server', 'sync-server.mjs')], { env, stdio: 'ignore' })
  const stop = () => {
    child.kill('SIGTERM')
  }

  try {
    for (let i = 0; i < 60; i++) {
      try {
        const res = await fetch(`${SYNC_URL}/health`)
        if (res.ok) break
      } catch {
        // not listening yet
      }
      if (i === 59) throw new Error(`sync server did not start on ${SYNC_URL}`)
      await sleep(250)
    }

    const cli = (...args) => run('node', [join(repo, 'server', 'cli.mjs'), ...args], { env })
    await cli('facility:add', FACILITY, 'CSB2 Ambohidratrimo', 'MG')
    const { stdout } = await cli('enrol:code', FACILITY)
    const code = stdout.match(/enrolment code:\s+(\S+)/)?.[1]
    if (!code) throw new Error(`could not read an enrolment code from:\n${stdout}`)

    console.log(`  sync      server on ${SYNC_URL}, facility ${FACILITY}`)
    return { code, stop }
  } catch (err) {
    stop()
    throw err
  }
}

/** Enrol through the real Settings form, the way a nurse would. */
async function enrolDevice(page, code) {
  await page.goto(`${BASE}/settings`, { waitUntil: 'networkidle2' })
  await settle(page)
  await unlockIfNeeded(page)

  const url = await page.waitForSelector('input[placeholder="https://sync.example.org"]')
  await url.click()
  await url.type(SYNC_URL)
  // The form persists the URL on blur, and the enrol button stays disabled
  // until it is set.
  await page.evaluate(() => document.activeElement?.blur())

  const codeInput = await page.waitForSelector('input[placeholder="ABCD-2345"]')
  await codeInput.click()
  await codeInput.type(code)

  await clickText(page, 'button', /enrol this device/)
  await page.waitForFunction(
    () => /device enrolled/i.test(document.body.textContent ?? ''),
    { timeout: 20_000 },
  )

  // Push what is already on the device, so the chip can honestly say everything
  // is synced rather than counting a backlog.
  await clickText(page, 'button', /sync now/)
  await page.waitForFunction(
    () => !/syncing/i.test(document.body.textContent ?? ''),
    { timeout: 30_000 },
  )
  await sleep(400)
  console.log('  sync      device enrolled and pushed')
}

/**
 * The offline sequence, captured live.
 *
 * A still cannot show that the network is off and the app still works, so this
 * walks it and photographs each step. Same walk `npm run smoke` asserts, which
 * means the video cannot show something CI does not also prove.
 */
async function captureOffline() {
  const dest = join(PUBLIC, 'offline')
  await rm(dest, { recursive: true, force: true })
  await mkdir(dest, { recursive: true })

  const sync = await startSyncServer()
  const browser = await puppeteer.launch({
    executablePath: await findChrome(),
    headless: 'new',
    args: LAUNCH_ARGS,
  })
  const page = await browser.newPage()
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 })

  let n = 0
  const shot = async (label) => {
    const name = `${String(++n).padStart(2, '0')}-${label}.png`
    await page.screenshot({ path: join(dest, name) })
    console.log(`  offline   ${name}`)
  }

  try {
    await page.goto(BASE, { waitUntil: 'networkidle2' })
    await settle(page)

    const inputs = await page.$$('input')
    const values = ['Dr Ranaivo', '4729', '4729']
    for (let i = 0; i < values.length && i < inputs.length; i++) {
      await inputs[i].click()
      await inputs[i].type(values[i])
    }
    await clickText(page, 'button', /create account/)

    await page.goto(`${BASE}/settings`, { waitUntil: 'networkidle2' })
    await settle(page)
    await unlockIfNeeded(page)
    await clickText(page, 'button', /load demo/)
    await sleep(600)

    await enrolDevice(page, sync.code)

    await page.goto(`${BASE}/patients`, { waitUntil: 'networkidle2' })
    await settle(page)
    await unlockIfNeeded(page)
    await shot('online-roster')

    // Network off. Everything after this is the claim being demonstrated.
    await page.setOfflineMode(true)
    await shot('offline-roster')

    await page.reload({ waitUntil: 'domcontentloaded' })
    await settle(page)
    await shot('offline-reload-lock')

    await unlockIfNeeded(page)
    await shot('offline-after-unlock')

    await page.goto(`${BASE}/patients`, { waitUntil: 'domcontentloaded' })
    await settle(page)
    await unlockIfNeeded(page)
    await shot('offline-roster-again')
  } finally {
    await browser.close()
    sync.stop()
  }
}

/**
 * The app's own typeface, so the video is set in the same type as the product.
 *
 * Copied from the root node_modules rather than re-downloaded: it is the exact
 * file the app ships and the service worker precaches, which is the point.
 */
async function copyFont() {
  const dest = join(PUBLIC, 'fonts')
  await mkdir(dest, { recursive: true })
  const name = 'ibm-plex-sans-latin-wght-normal.woff2'
  await copyFile(
    join(repo, 'node_modules', '@fontsource-variable', 'ibm-plex-sans', 'files', name),
    join(dest, name),
  )
  console.log(`  font      ${name}`)
}

async function main() {
  console.log('capturing the real app for the demo video\n')
  await mkdir(PUBLIC, { recursive: true })
  await copyFont()
  await copyScreens()
  await captureOffline()
  console.log('\n  -> video/public/. Every frame is the running application.')
}

main().catch((err) => {
  console.error(`capture failed: ${err.message}`)
  process.exit(1)
})
